import { colorTokens, spacingTokens, borderRadiusTokens, shadowTokens } from './tokens.js';

export const themes = {
  light: {
    name: 'light',
    background: '#f7f9fc',
    surface: '#ffffff',
    surfaceAlt: '#eef4fb',
    elevated: '#ffffff',
    text: '#0f172a',
    secondaryText: '#475569',
    mutedText: '#64748b',
    border: '#e2e8f0',
    borderStrong: '#cbd5e1',
    primary: colorTokens.primary[600],
    primaryHover: colorTokens.primary[700],
    primarySoft: '#dbeafe',
    success: colorTokens.success[500],
    warning: colorTokens.warning[500],
    danger: colorTokens.danger[500],
    shadow: shadowTokens.soft,
    spacing: spacingTokens,
    borderRadius: borderRadiusTokens,
  },
  dark: {
    name: 'dark',
    background: '#07111f',
    surface: '#0c1728',
    surfaceAlt: '#111f34',
    elevated: '#14233a',
    text: '#f8fafc',
    secondaryText: '#cbd5e1',
    mutedText: '#94a3b8',
    border: '#21324b',
    borderStrong: '#334155',
    primary: colorTokens.primary[400],
    primaryHover: colorTokens.primary[300],
    primarySoft: 'rgba(96, 165, 250, 0.14)',
    success: colorTokens.success[500],
    warning: colorTokens.warning[500],
    danger: colorTokens.danger[500],
    shadow: shadowTokens.dark,
    spacing: spacingTokens,
    borderRadius: borderRadiusTokens,
  },
  system: {
    name: 'system',
    background: 'var(--theme-background)',
    surface: 'var(--theme-surface)',
    surfaceAlt: 'var(--theme-surface-alt)',
    text: 'var(--theme-text)',
    secondaryText: 'var(--theme-secondary-text)',
    border: 'var(--theme-border)',
    primary: colorTokens.primary[500],
    primaryHover: colorTokens.primary[600],
    success: colorTokens.success[500],
    warning: colorTokens.warning[500],
    danger: colorTokens.danger[500],
    shadow: '0 20px 45px rgba(15, 23, 42, 0.12)',
    spacing: spacingTokens,
    borderRadius: borderRadiusTokens,
  },
};
